"use client";

import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import { DailyLog, User } from "@/types";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica" },
  header: { marginBottom: 20, borderBottom: 1, paddingBottom: 10, borderColor: "#e5e7eb" },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#6b7280" },
  logEntry: { marginBottom: 16, paddingBottom: 12, borderBottom: 1, borderColor: "#f3f4f6" },
  logTitle: { fontSize: 12, fontWeight: "bold", marginBottom: 2 },
  logDate: { fontSize: 9, color: "#6b7280", marginBottom: 6 },
  logContent: { fontSize: 10, lineHeight: 1.6 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#9ca3af" },
});

interface DailyLogPDFProps {
  user: { name: string; email: string };
  logs: DailyLog[];
}

function DailyLogPDF({ user, logs }: DailyLogPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Daily Log - {user.name}</Text>
          <Text style={styles.subtitle}>{user.email} &bull; {logs.length} entries</Text>
        </View>
        {logs.map((log) => (
          <View key={log.id} style={styles.logEntry}>
            <Text style={styles.logTitle}>{log.title}</Text>
            <Text style={styles.logDate}>{log.log_date}</Text>
            <Text style={styles.logContent}>{log.content}</Text>
          </View>
        ))}
        <Text style={styles.footer}>Generated by TeamVora &bull; {new Date().toLocaleDateString("id-ID")}</Text>
      </Page>
    </Document>
  );
}

export async function generateDailyLogPdf(user: { name: string; email: string }, logs: DailyLog[]) {
  const blob = await pdf(<DailyLogPDF user={user} logs={logs} />).toBlob();
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `daily-log-${user.name}-${new Date().toISOString().split("T")[0]}.pdf`;
  link.click();
  URL.revokeObjectURL(url);
}
