import { ProjectDocPage } from "./types";

export const databasePages: ProjectDocPage[] = [
{
    id: "database/overview",
    slug: ["database", "overview"],
    category: "database",
    title: "Database Overview",
    summary:
      "Ringkasan database TeamVora: runtime DB aktif, strategi migration, pembagian domain tabel, dan perbedaan antara database lokal contoh dengan runtime production-like database.",
    audience: ["Backend Developer", "DB Reviewer", "Super Admin"],
    overallStatus: "Verified",
    statusNote:
      "Audit backend menunjukkan DB runtime saat ini adalah PostgreSQL, sementara SQLite lokal tetap ada sebagai fallback/dev artifact tetapi bukan sumber kebenaran runtime.",
    facts: [
      { label: "Runtime DB", value: "PostgreSQL (pgsql)" },
      { label: "Dev Fallback", value: "SQLite tersedia tetapi bukan runtime utama" },
      { label: "Primary Schema Strategy", value: "Laravel migrations + alter migrations bertahap" },
      { label: "Domain Count", value: "Identity, Teams, Finance, Productivity, Media, CMS, Support, Ops" },
    ],
    responsibilities: [
      "Menjelaskan sumber kebenaran database runtime yang benar untuk dokumentasi internal.",
      "Menjadi pintu masuk sebelum pembaca masuk ke schema map atau domain tabel yang lebih detail.",
      "Menandai area migration yang sensitif, termasuk ketergantungan tertentu pada PostgreSQL.",
    ],
    keyFiles: [
      {
        path: "Backend/config/database.php",
        note: "Daftar driver dan konfigurasi connection database/redis.",
        status: "Verified",
      },
      { path: "Backend/database/migrations", note: "Semua skema tabel dan alter schema TeamVora.", status: "Verified" },
      { path: "Backend/app/Models", note: "Model yang memetakan tabel domain utama.", status: "Verified" },
      {
        path: "Backend/composer.json",
        note: "Menunjukkan Laravel migration/testing toolchain backend.",
        status: "Verified",
      },
    ],
    flows: [
      {
        title: "Sumber kebenaran database",
        status: "Verified",
        steps: [
          "Config database mendukung sqlite, mysql, mariadb, pgsql, dan sqlsrv.",
          "Runtime yang terverifikasi saat audit adalah pgsql.",
          "SQLite lokal tidak boleh dipakai sebagai acuan utama dokumentasi schema runtime, terutama untuk area yang telah memakai migration PostgreSQL-specific.",
        ],
      },
      {
        title: "Pertumbuhan schema",
        status: "Verified",
        steps: [
          "Skema TeamVora dibangun lewat create migrations lalu diikuti alter migrations yang menyesuaikan field/constraint agar cocok dengan controller/frontend saat ini.",
          "Multi-team support tampak ditambahkan belakangan lewat migration yang menyuntikkan team_id ke banyak tabel domain.",
        ],
      },
    ],
    dependencies: [
      "Laravel migrations.",
      "Runtime PostgreSQL.",
      "Model Eloquent.",
      "Controllers dan resources yang memanfaatkan field-field hasil migration.",
    ],
    sensitiveAreas: [
      {
        title: "SQLite assumptions",
        detail:
          "Men-debug dengan asumsi SQLite bisa menyesatkan karena runtime utama adalah PostgreSQL dan ada migration yang PostgreSQL-specific.",
        status: "Verified",
      },
      {
        title: "Alter migrations",
        detail:
          "Banyak tabel domain berkembang melalui alter migrations; pembaca harus melihat create + alter untuk memahami schema final, bukan hanya migration pertama.",
        status: "Verified",
      },
      {
        title: "UUID dan integer keys bercampur",
        detail:
          "TeamVora memakai kombinasi PK UUID dan integer/bigint, sehingga relasi dan binding perlu diperhatikan saat mengubah model atau frontend params.",
        status: "Verified",
      },
    ],
    safeChangeGuide: [
      "Saat mengaudit tabel, baca seluruh rantai migration create + alter yang memengaruhi tabel tersebut.",
      "Jangan menyamakan local dev artifact dengan runtime production source of truth.",
      "Jika mengubah type/constraint, audit model cast, controller query, resource output, dan types frontend yang berkaitan.",
    ],
    validationChecklist: [
      "Jalankan migrate status dan pastikan migration chain dapat dipahami pada environment target.",
      "Tes minimal satu alur CRUD pada domain yang field-nya diubah.",
      "Verifikasi schema-specific queries bila migration menyentuh constraint/index atau enum/status fields.",
    ],
    affectedSurfaces: [
      "Backend/config/database.php",
      "Backend/database/migrations/*",
      "Backend/app/Models/*",
      "Backend/app/Http/Controllers/Api/*",
    ],
    relatedPageIds: [
      "database/schema-map",
      "database/users-teams",
      "database/finance",
      "reference/architecture-decisions",
    ],
  },
{
    id: "database/schema-map",
    slug: ["database", "schema-map"],
    category: "database",
    title: "Schema Map & Relationships",
    summary:
      "Peta relasi antar domain database TeamVora: identity, tenancy, finance, productivity, media, content, support, notifications, dan audit tables.",
    audience: ["Backend Developer", "QA", "Architect"],
    overallStatus: "Verified",
    statusNote:
      "Tabel-tabel utama dan migration source-nya dapat diverifikasi langsung dari daftar migration backend saat ini.",
    facts: [
      { label: "Identity Tables", value: "users, personal_access_tokens, sessions, password_reset_tokens" },
      { label: "Tenancy Tables", value: "teams, team_invitations" },
      {
        label: "Finance Tables",
        value: "cash_books, split_bills, bill_items, recurring_bills, recurring_bill_generations",
      },
      { label: "Ops Tables", value: "notifications, activity_log, jobs, failed_jobs, settings, email_settings" },
    ],
    responsibilities: [
      "Menyediakan peta lintas-domain sebelum pembaca masuk ke halaman tabel yang lebih granular.",
      "Membantu memahami arah relasi dari user/team ke modul bisnis lainnya.",
      "Menunjukkan bahwa beberapa domain memakai UUID, beberapa lainnya integer IDs.",
    ],
    keyFiles: [
      {
        path: "Backend/database/migrations/0001_01_01_000000_create_users_table.php",
        note: "Identity table dasar users, sessions, password reset tokens.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_03_000001_create_teams_table.php",
        note: "Table teams sebagai wadah tenancy.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_03_000002_add_team_id_to_tables.php",
        note: "Injection multi-team context ke banyak tabel bisnis.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_132012_create_cash_books_table.php",
        note: "Awal domain finance cash book.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_132015_create_tasks_table.php",
        note: "Awal domain task/productivity.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_03_000003_create_blogs_table.php",
        note: "Awal domain blog/CMS.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_07_043232_create_tickets_table.php",
        note: "Support ticket domain.",
        status: "Verified",
      },
    ],
    flows: [
      {
        title: "Hub relasi utama",
        status: "Verified",
        steps: [
          "User berada di pusat identity dan memiliki role, permission, dan team aktif.",
          "Team menjadi konteks untuk finance, productivity, media, blog tertentu, invitations, dan anggota.",
          "Finance, productivity, media, chat, dan support kemudian bercabang dari konteks team dan/atau user.",
        ],
      },
      {
        title: "Ops tables",
        status: "Verified",
        steps: [
          "notifications dan activity_log mendukung observability/audit dari aktivitas user dan sistem.",
          "jobs/failed_jobs/job_batches mendukung queue runtime database.",
          "settings dan email_settings mendukung konfigurasi dan branding platform dari sisi data.",
        ],
      },
    ],
    dependencies: [
      "Migration create + alter files.",
      "Model casts dan relations.",
      "Controllers yang memfilter team_id atau user_id.",
    ],
    sensitiveAreas: [
      {
        title: "team_id ditambahkan belakangan",
        detail:
          "Karena tenancy injection datang melalui migration tambahan, sebagian logic lama bisa saja tidak seketat modul baru dalam membatasi data per tim.",
        status: "Verified",
      },
      {
        title: "Mixed key strategy",
        detail:
          "Relasi antar tabel perlu diaudit hati-hati karena beberapa tabel berbasis UUID sementara lainnya integer/bigint.",
        status: "Verified",
      },
      {
        title: "Audit vs business tables",
        detail:
          "Jangan mencampur activity_log/notifications/jobs sebagai domain bisnis utama; mereka adalah supporting operational tables.",
        status: "Inferred",
      },
    ],
    safeChangeGuide: [
      "Mulai perubahan schema dari domain tertentu, lalu pantau semua relasi keluar-masuk dari tabel inti domain itu.",
      "Jika menambah foreign key ke tabel UUID atau integer, pastikan tipe kolom dan route model binding tetap konsisten.",
      "Perbarui docs domain page yang relevan setelah migration baru ditambahkan.",
    ],
    validationChecklist: [
      "Pastikan migration chain masih logis untuk environment target.",
      "Verifikasi relasi model dan eager loading yang dipakai resource/controller.",
      "Tes alur create/update/delete pada domain terkait jika relasi diubah.",
    ],
    affectedSurfaces: [
      "Backend/database/migrations/*",
      "Backend/app/Models/*",
      "Backend/app/Http/Resources/*",
      "Frontend/src/types/api.ts",
    ],
    relatedPageIds: [
      "database/users-teams",
      "database/finance",
      "database/productivity",
      "database/content-media-support",
    ],
  },
{
    id: "database/users-teams",
    slug: ["database", "users-teams"],
    category: "database",
    title: "Users & Teams",
    summary:
      "Detail tabel identity dan tenancy: users, teams, team_invitations, roles/permissions pivots, serta hubungan antara user, role, permission, dan konteks tim.",
    audience: ["Backend Developer", "Super Admin", "QA"],
    overallStatus: "Verified",
    statusNote:
      "Migration users/teams/permissions dan model terkait cukup jelas untuk memetakan identity + tenancy layer TeamVora saat ini.",
    facts: [
      { label: "Core Tables", value: "users, teams, team_invitations" },
      {
        label: "RBAC Tables",
        value: "roles, permissions, model_has_roles, model_has_permissions, role_has_permissions",
      },
      { label: "Role Encoding", value: "users.role + Spatie roles" },
      { label: "Invite Model", value: "token + email + status + expiry" },
    ],
    responsibilities: [
      "Menjelaskan bagaimana user dihubungkan ke team dan bagaimana role bekerja dalam konteks TeamVora.",
      "Menjadi referensi utama ketika ada perubahan pada onboarding tim, invitation, member management, atau impersonation.",
      "Membantu membedakan identity fields vs permission system fields.",
    ],
    keyFiles: [
      {
        path: "Backend/database/migrations/0001_01_01_000000_create_users_table.php",
        note: "Membuat users, password_reset_tokens, sessions.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_03_000001_create_teams_table.php",
        note: "Membuat teams dan relasi leader ke user.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_03_000004_create_team_invitations_table.php",
        note: "Membuat table undangan tim.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_131958_create_permission_tables.php",
        note: "Membuat seluruh tabel role/permission Spatie.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_03_000002_add_team_id_to_tables.php",
        note: "Menambahkan team_id dan role ke users serta team_id ke tabel domain lain.",
        status: "Verified",
      },
      {
        path: "Backend/app/Models/User.php",
        note: "Definisi relasi team/roles/permissions/token pada user.",
        status: "Verified",
      },
      {
        path: "Backend/app/Models/Team.php",
        note: "Relasi team ke leader, members, settings/logo.",
        status: "Verified",
      },
    ],
    flows: [
      {
        title: "User onboarding ke team",
        status: "Verified",
        steps: [
          "User bisa register tanpa team atau membuat team baru saat register, tergantung input team_name.",
          "Undangan tim menggunakan token dan email untuk accept flow publik.",
          "Setelah user tergabung ke team, role/permission dan team context akan memengaruhi route serta menu frontend.",
        ],
      },
      {
        title: "Role state",
        status: "Verified",
        steps: [
          "Role tampak direpresentasikan sebagai kolom users.role sekaligus Spatie roles.",
          "Frontend banyak membaca role string langsung untuk redirect/layout, sementara permission granular memfilter menu tertentu.",
        ],
      },
    ],
    dependencies: [
      "AuthController register/login/me.",
      "TeamController dan MemberController.",
      "Spatie Permission configuration and seeders.",
      "Frontend auth-store, admin users/team pages, lead/member sidebars.",
    ],
    sensitiveAreas: [
      {
        title: "Role drift",
        detail:
          "Karena role hidup di kolom users.role dan Spatie tables, ketidaksinkronan dapat menyebabkan redirect frontend dan hak akses backend tidak sejalan.",
        status: "Verified",
      },
      {
        title: "Team deletion",
        detail:
          "Penghapusan tim sangat destruktif karena berdampak ke anggota non-superadmin, finance data, blog, media, dan assets tim.",
        status: "Verified",
      },
      {
        title: "Invitation lifecycle",
        detail:
          "Accept invitation adalah endpoint publik, jadi perubahan token/expiry/role assignment harus diaudit ketat.",
        status: "Verified",
      },
    ],
    safeChangeGuide: [
      "Saat mengubah role/team model, audit register flow, invitation flow, user admin panel, dan sidebar/frontend guards.",
      "Dokumentasikan apakah perubahan baru memodifikasi users.role, Spatie roles, atau keduanya.",
      "Tambahkan verifikasi khusus untuk impersonation bila identity model disentuh.",
    ],
    validationChecklist: [
      "Tes register tanpa team dan dengan team baru.",
      "Tes invitation accept flow dengan user existing/non-existing sesuai requirement sistem.",
      "Tes update role dari admin dan lihat dampaknya di menu lead/member serta akses endpoint.",
    ],
    affectedSurfaces: [
      "Backend/app/Http/Controllers/Api/AuthController.php",
      "Backend/app/Http/Controllers/Api/TeamController.php",
      "Backend/app/Http/Controllers/Api/MemberController.php",
      "Frontend/src/app/admin/users/**/*",
      "Frontend/src/app/admin/teams/**/*",
      "Frontend/src/components/layout/sidebar.tsx",
    ],
    relatedPageIds: [
      "backend/auth-rbac",
      "frontend/routes-role-surfaces",
      "operations/superadmin-handbook",
      "reference/glossary",
    ],
  },
{
    id: "database/finance",
    slug: ["database", "finance"],
    category: "database",
    title: "Finance Domain",
    summary:
      "Dokumentasi tabel finance TeamVora: cash_books, split_bills, bill_items, recurring_bills, recurring_bill_generations, termasuk enum/status dan keterkaitan ke layar lead/member.",
    audience: ["Backend Developer", "QA", "Team Ops"],
    overallStatus: "Verified",
    statusNote:
      "Migration finance domain dan model/controllers terkait cukup jelas. Ada juga beberapa temuan sensitif pada query dashboard recurring yang tidak selaras dengan schema saat ini.",
    facts: [
      { label: "Cash Book PK", value: "UUID" },
      { label: "Split Bill PK", value: "UUID" },
      { label: "Recurring Bill Status", value: "active, paused, ended" },
      { label: "Bill Item Status", value: "unpaid, pending_verification, paid" },
    ],
    responsibilities: [
      "Menjelaskan model data pembukuan, tagihan bersama, verifikasi pembayaran, dan tagihan berulang.",
      "Membantu membedakan cash transaction manual vs generated recurring bill lifecycle.",
      "Menjadi referensi untuk finance screens di lead/member dan scheduler backend.",
    ],
    keyFiles: [
      {
        path: "Backend/database/migrations/2026_07_02_132012_create_cash_books_table.php",
        note: "Membuat cash_books dengan type in/out, amount, date, created_by.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_132013_create_split_bills_table.php",
        note: "Membuat split_bills awal.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_135702_alter_split_bills_for_controller.php",
        note: "Mengubah created_by -> creator_id, date -> due_date, status menjadi string active.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_132016_create_bill_items_table.php",
        note: "Membuat bill_items awal.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_135620_alter_bill_items_table.php",
        note: "Mengganti is_paid dengan status/proof_path/verified_by/verified_at.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_140001_create_recurring_bills_table.php",
        note: "Recurring bill core fields: frequency, interval_days, due_day, status, next_generation_at.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_140004_create_recurring_bill_generations_table.php",
        note: "Histori generation recurring bill.",
        status: "Verified",
      },
    ],
    flows: [
      {
        title: "Split bill lifecycle",
        status: "Verified",
        steps: [
          "Lead/member membuat split bill dengan creator_id dan due_date dalam konteks team.",
          "Bill items dibagi per user, lalu user dapat pay dengan proof dan verifier dapat verify item tersebut.",
          "Status item dan split bill menjadi dasar tampilan finance screens dan reminder flow.",
        ],
      },
      {
        title: "Recurring bill lifecycle",
        status: "Verified",
        steps: [
          "Recurring bill bertindak sebagai template tagihan berulang per team.",
          "Scheduler atau action manual dapat generate split bill baru dari recurring bill.",
          "Histori generation direkam di recurring_bill_generations dan split bill baru dapat menunjuk parent_recurring_bill_id.",
        ],
      },
    ],
    dependencies: [
      "CashBookController, SplitBillController, BillItemController, RecurringBillController.",
      "GenerateRecurringBills dan RemindBillItems commands.",
      "Lead/member finance routes dan types frontend.",
    ],
    sensitiveAreas: [
      {
        title: "Recurring dashboard mismatch",
        detail:
          "Ada temuan bahwa query dashboard recurring bills memakai kolom yang tidak sepenuhnya selaras dengan schema/model saat ini, sehingga area dashboard finance perlu diperiksa saat ada perubahan recurring domain.",
        status: "Verified",
      },
      {
        title: "Proof and verification flow",
        detail:
          "Perubahan status bill item atau field proof/verification akan berdampak langsung ke pembayaran user dan audit verifikasi tim.",
        status: "Verified",
      },
      {
        title: "Generated vs manual bills",
        detail:
          "Split bills manual dan hasil generation recurring terhubung melalui parent_recurring_bill_id; perubahan di salah satu sisi bisa memutus histori atau tampilan relasi jika tidak konsisten.",
        status: "Verified",
      },
    ],
    safeChangeGuide: [
      "Saat mengubah finance schema, audit backend controllers, recurring service, scheduler, resource output, dan screens lead/member secara bersamaan.",
      "Pisahkan perubahan cash_books dari split_bills/recurring bila tidak benar-benar saling terkait.",
      "Jika menambah status enum/string baru, update docs, filters, badge UI, dan validasi form di frontend.",
    ],
    validationChecklist: [
      "Tes create/update/delete cash book.",
      "Tes create split bill, bayar bill item, dan verify bill item.",
      "Tes create recurring bill dan generate satu siklus split bill darinya.",
    ],
    affectedSurfaces: [
      "Backend/app/Http/Controllers/Api/CashBookController.php",
      "Backend/app/Http/Controllers/Api/SplitBillController.php",
      "Backend/app/Http/Controllers/Api/BillItemController.php",
      "Backend/app/Http/Controllers/Api/RecurringBillController.php",
      "Frontend/src/app/lead/finance/**/*",
      "Frontend/src/app/member/finance/**/*",
      "Frontend/src/types/api.ts",
    ],
    relatedPageIds: [
      "backend/jobs-realtime-storage",
      "operations/superadmin-handbook",
      "database/schema-map",
      "database/users-teams",
    ],
  },
{
    id: "database/productivity",
    slug: ["database", "productivity"],
    category: "database",
    title: "Productivity Domain",
    summary:
      "Dokumentasi tabel productivity TeamVora: tasks dan daily_logs, termasuk status task, priority, position, attachment, dan relasinya ke team serta user.",
    audience: ["Backend Developer", "Frontend Developer", "QA"],
    overallStatus: "Verified",
    statusNote:
      "Tasks dan daily logs dapat dipetakan cukup jelas dari migration create/alter, model, controller, dan route frontend terkait.",
    facts: [
      { label: "Task PK", value: "UUID" },
      { label: "Task Status", value: "todo, in_progress, done" },
      { label: "Task Priority", value: "low, medium, high" },
      { label: "Daily Log PK", value: "UUID" },
    ],
    responsibilities: [
      "Menjelaskan bagaimana productivity data disimpan dan dipakai di board/list frontend.",
      "Membedakan task metadata (status, priority, position, assignee, creator) dari daily log metadata (log_date, title, content, attachment).",
      "Menjadi rujukan saat mengubah task board, reorder behavior, atau export/report harian.",
    ],
    keyFiles: [
      {
        path: "Backend/database/migrations/2026_07_02_132015_create_tasks_table.php",
        note: "Membuat tasks awal.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_135830_alter_tasks_for_controller.php",
        note: "Mengubah assigned_to -> assignee_id, menambah priority dan creator_id.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_06_000001_add_position_to_tasks_table.php",
        note: "Menambah position untuk reorder/task board ordering.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_132014_create_daily_logs_table.php",
        note: "Membuat daily_logs awal.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_135951_alter_daily_logs_table.php",
        note: "Menambah title pada daily_logs.",
        status: "Verified",
      },
      {
        path: "Backend/app/Models/Task.php",
        note: "Model task beserta casts dan relations yang relevan.",
        status: "Verified",
      },
      {
        path: "Backend/app/Models/DailyLog.php",
        note: "Model daily log dan attachment semantics.",
        status: "Verified",
      },
    ],
    flows: [
      {
        title: "Task board flow",
        status: "Verified",
        steps: [
          "Task dibuat dengan creator, optional assignee, due_date, priority, dan status.",
          "Task dapat berganti status atau di-reorder memakai field position.",
          "Lead/member pages menampilkan task berdasarkan filter dan status board/list masing-masing.",
        ],
      },
      {
        title: "Daily log flow",
        status: "Verified",
        steps: [
          "User membuat daily log dengan title, log_date, content, dan optional attachment.",
          "Backend menyediakan export endpoint untuk daily logs.",
          "Daily log dipakai sebagai catatan aktivitas harian tim.",
        ],
      },
    ],
    dependencies: [
      "TaskController dan DailyLogController.",
      "Lead/member productivity pages.",
      "Storage backend untuk attachment daily log bila ada file.",
    ],
    sensitiveAreas: [
      {
        title: "Object access per team/user",
        detail:
          "Task dan daily log adalah domain yang mudah terkena masalah object-level authorization bila filter team/user tidak konsisten di semua endpoint.",
        status: "Verified",
      },
      {
        title: "Task reorder semantics",
        detail:
          "Perubahan field position atau endpoint reorder bisa merusak urutan visual board dan menimbulkan drift antar user/session.",
        status: "Verified",
      },
      {
        title: "Attachment handling",
        detail:
          "Daily log attachment menyentuh storage flow yang sama-sama sensitif terhadap orphan file atau path mismatch.",
        status: "Inferred",
      },
    ],
    safeChangeGuide: [
      "Audit create/show/update/delete/reorder together jika mengubah task schema atau board behavior.",
      "Jika menambah status task baru, update semua filter, label, dan board columns yang bergantung padanya.",
      "Jika mengubah daily log field, audit export endpoint dan pages create/edit/list.",
    ],
    validationChecklist: [
      "Tes create/edit/delete task.",
      "Tes patch status dan reorder task.",
      "Tes create/edit/delete daily log dan export endpoint bila touched.",
    ],
    affectedSurfaces: [
      "Backend/app/Http/Controllers/Api/TaskController.php",
      "Backend/app/Http/Controllers/Api/DailyLogController.php",
      "Frontend/src/app/lead/productivity/**/*",
      "Frontend/src/app/member/productivity/**/*",
      "Frontend/src/types/api.ts",
    ],
    relatedPageIds: [
      "frontend/routes-role-surfaces",
      "backend/api-surface",
      "database/users-teams",
      "operations/superadmin-handbook",
    ],
  },
{
    id: "database/content-media-support",
    slug: ["database", "content-media-support"],
    category: "database",
    title: "Content, Media & Support",
    summary:
      "Dokumentasi tabel blog/CMS, categories, team_media, conversations/messages, tickets, contact_messages, notifications, settings, dan email_settings.",
    audience: ["Backend Developer", "Frontend Developer", "Support Engineer"],
    overallStatus: "Verified",
    statusNote:
      "Domain ini tersebar di beberapa migration dan model, tetapi hubungan besarnya cukup jelas: konten publik, aset media, komunikasi internal, dan operasional support/platform.",
    facts: [
      { label: "Blog Tables", value: "blogs, categories" },
      { label: "Media Table", value: "team_media" },
      { label: "Communication Tables", value: "conversations, conversation_participants, messages, notifications" },
      { label: "Support Tables", value: "tickets, contact_messages, settings, email_settings" },
    ],
    responsibilities: [
      "Menjelaskan domain non-finance/non-productivity yang tetap kritis untuk operasional platform dan brand presence.",
      "Membantu memahami hubungan antara blog/public pages, media assets, chat, support, dan admin settings data.",
      "Menjadi referensi saat mengubah marketing CMS, chat retention, atau support workflow.",
    ],
    keyFiles: [
      {
        path: "Backend/database/migrations/2026_07_03_000003_create_blogs_table.php",
        note: "Blog table awal.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_07_000002_create_categories_table.php",
        note: "Kategori blog.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_07_000001_add_seo_fields_to_blogs_table.php",
        note: "SEO fields untuk blog.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_02_133454_create_team_media_table.php",
        note: "Media storage metadata table.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_07_044858_create_conversations_table.php",
        note: "Conversation table untuk chat.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_07_043232_create_tickets_table.php",
        note: "Support ticket table.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_03_171631_create_settings_table.php",
        note: "Settings key-value-group untuk platform/admin/public content.",
        status: "Verified",
      },
      {
        path: "Backend/database/migrations/2026_07_03_173444_create_email_settings_table.php",
        note: "Email branding/config data layer.",
        status: "Verified",
      },
    ],
    flows: [
      {
        title: "CMS and public content",
        status: "Verified",
        steps: [
          "Blog dan categories menopang content/public publishing.",
          "Blogs memiliki SEO fields dan status evolution termasuk scheduled support.",
          "Admin screens untuk marketing/settings hidup berdampingan dengan data settings platform yang sebagian dapat dipakai surface publik.",
        ],
      },
      {
        title: "Media, chat, and support",
        status: "Verified",
        steps: [
          "team_media menyimpan metadata asset untuk dokumen/galeri/chat attachment.",
          "conversations/messages menopang DM atau percakapan tim dengan cleanup retention terjadwal.",
          "tickets dan contact_messages menangani support dari internal role atau publik.",
        ],
      },
    ],
    dependencies: [
      "BlogController, CategoryController, MediaController, ChatController, Ticket controllers, ContactController.",
      "R2 storage flow.",
      "Frontend admin blog/media/tickets/settings pages serta marketing public pages.",
    ],
    sensitiveAreas: [
      {
        title: "Marketing content parity",
        detail:
          "Tidak semua data settings/admin editors terlihat sudah dikonsumsi sepenuhnya oleh halaman marketing publik saat ini.",
        status: "Partial",
      },
      {
        title: "Chat retention and media cleanup",
        detail:
          "Messages dan attachment chat mengalami cleanup otomatis 7 hari, sehingga perubahan schema/chat media perlu memperhatikan retention workflow.",
        status: "Verified",
      },
      {
        title: "Support + settings overlap",
        detail:
          "tickets, contact messages, settings, dan email settings semua berada di domain operasional yang sensitif untuk superadmin.",
        status: "Verified",
      },
    ],
    safeChangeGuide: [
      "Pisahkan perubahan CMS dari perubahan support/settings bila memungkinkan agar scope tidak melebar.",
      "Jika mengubah blog fields, audit SEO metadata, public blog pages, admin blog editor, dan src/types/api.ts.",
      "Jika mengubah team_media usage, audit semua alur upload/delete termasuk chat dan gallery/documents screens.",
    ],
    validationChecklist: [
      "Tes create/edit/delete blog dan category.",
      "Tes upload media dan delete media.",
      "Tes ticket flow dan contact management bila tersentuh.",
      "Tes chat attachment flow bila schema/media path diubah.",
    ],
    affectedSurfaces: [
      "Backend/app/Http/Controllers/Api/BlogController.php",
      "Backend/app/Http/Controllers/Api/MediaController.php",
      "Backend/app/Http/Controllers/Api/ChatController.php",
      "Backend/app/Http/Controllers/Api/TicketController.php",
      "Backend/app/Http/Controllers/Api/ContactController.php",
      "Frontend/src/app/admin/blogs/**/*",
      "Frontend/src/app/admin/media/page.tsx",
      "Frontend/src/components/chat/*",
    ],
    relatedPageIds: [
      "operations/media-storage",
      "operations/email-notifications-support",
      "frontend/routes-role-surfaces",
      "database/schema-map",
    ],
  },
{
    id: "database/table-users",
    slug: ["database", "table-users"],
    category: "database",
    title: "Table: users",
    summary: "Master user table untuk auth, profile, membership team, role string internal, dan integrasi RBAC.",
    audience: ["Backend Developer", "Super Admin", "QA"],
    overallStatus: "Verified",
    statusNote: "users adalah pusat identity layer dan dipakai bersama Sanctum serta Spatie roles/permissions.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Important Constraints", value: "email unique, phone unique nullable" },
      { label: "Key Relations", value: "team_id -> teams.id" },
      { label: "Role Storage", value: "users.role string + Spatie RBAC tables" },
    ],
    responsibilities: [
      "Menyimpan identitas akun, profil dasar, dan konteks role/team aktif user.",
      "Menjadi anchor utama untuk auth, membership, assignment, verification, chat, ticketing, dan CMS authorship.",
    ],
    keyFiles: [
      { path: "Backend/database/migrations/0001_01_01_000000_create_users_table.php", note: "Membuat users, password_reset_tokens, sessions.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_03_000002_add_team_id_to_tables.php", note: "Menambahkan team_id dan role string ke users.", status: "Verified" },
      { path: "Backend/app/Models/User.php", note: "Model user dengan HasApiTokens, HasRoles, Notifiable, dan relasi domain lain.", status: "Verified" },
    ],
    flows: [
      { title: "User identity flow", status: "Verified", steps: ["AuthController membuat dan memutakhirkan user.", "Frontend auth bootstrap membaca payload UserResource dari /login, /register, dan /me.", "Relasi team/role/permissions kemudian memengaruhi semua role surfaces frontend."] },
    ],
    dependencies: ["Sanctum", "Spatie Permission", "Team model", "Frontend auth-store/AuthProvider"],
    sensitiveAreas: [
      { title: "Dual role source", detail: "Role hidup di users.role dan juga di tabel Spatie, sehingga sinkronisasi selalu penting.", status: "Verified" },
    ],
    safeChangeGuide: ["Jika mengubah kolom user, audit AuthController, UserResource, dan src/types/api.ts.", "Jangan ubah semantics role/team tanpa memeriksa frontend redirect dan sidebar."] ,
    validationChecklist: ["Tes login/register/me.", "Tes update role/team user.", "Tes screens admin users dan auth flow frontend."],
    affectedSurfaces: ["Backend/app/Models/User.php", "Backend/app/Http/Controllers/Api/AuthController.php", "Frontend/src/types/api.ts"],
    relatedPageIds: ["backend/api-auth-profile", "database/table-teams", "backend/auth-rbac"],
  },
{
    id: "database/table-teams",
    slug: ["database", "table-teams"],
    category: "database",
    title: "Table: teams",
    summary: "Tabel inti tenancy/team yang memayungi finance, productivity, media, invitation, dan membership TeamVora.",
    audience: ["Backend Developer", "Super Admin"],
    overallStatus: "Verified",
    statusNote: "teams adalah pusat konteks multi-team TeamVora dan banyak operasi platform bergantung padanya.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Unique Field", value: "slug" },
      { label: "Important FK", value: "leader_id -> users.id" },
      { label: "Optional Settings", value: "settings json, logo_url nullable" },
    ],
    responsibilities: [
      "Menjadi wadah tenancy dan identitas tiap tim di platform.",
      "Menyimpan leader, slug, logo, dan konfigurasi ringan tingkat tim.",
    ],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_03_000001_create_teams_table.php", note: "Membuat tabel teams dengan slug unique dan leader relation.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_05_181705_add_logo_url_to_teams_table.php", note: "Menambah logo_url pada teams.", status: "Verified" },
      { path: "Backend/app/Models/Team.php", note: "Relasi leader, members, dan data domain tim lainnya.", status: "Verified" },
    ],
    flows: [
      { title: "Team tenancy flow", status: "Verified", steps: ["Team dipakai sebagai konteks membership dan domain bisnis seperti finance/productivity/media.", "Superadmin mengelola registry team dari admin panel dan TeamController.", "Lead/team flows bergantung pada team_id di user dan tabel domain lain."] },
    ],
    dependencies: ["User table", "TeamController", "Domain tables dengan team_id"],
    sensitiveAreas: [
      { title: "Team deletion cascade", detail: "Penghapusan tim bisa menghapus data lintas domain dan asset file yang luas.", status: "Verified" },
    ],
    safeChangeGuide: ["Audit semua tabel domain dengan team_id jika mengubah semantics teams.", "Jika mengubah slug/leader/logo behavior, tes admin teams dan lead settings terkait."],
    validationChecklist: ["Tes team CRUD.", "Tes upload logo tim.", "Tes switch team dan member listing."],
    affectedSurfaces: ["Backend/app/Models/Team.php", "Backend/app/Http/Controllers/Api/TeamController.php", "Frontend/src/app/admin/teams/**/*"],
    relatedPageIds: ["backend/api-teams-members", "database/table-users", "database/schema-map"],
  },
{
    id: "database/table-team-invitations",
    slug: ["database", "table-team-invitations"],
    category: "database",
    title: "Table: team_invitations",
    summary: "Tabel invitation berbasis token untuk onboarding anggota ke team.",
    audience: ["Backend Developer", "Super Admin", "QA"],
    overallStatus: "Verified",
    statusNote: "team_invitations jelas digunakan oleh TeamInvitationController dan notifikasi undangan.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Unique Field", value: "token" },
      { label: "Important FKs", value: "team_id -> teams.id, invited_by -> users.id" },
      { label: "Status Enum", value: "pending, accepted, expired" },
    ],
    responsibilities: ["Menyimpan token, email target, status, dan expiry invitation team.", "Menjadi basis flow accept invitation publik."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_03_000004_create_team_invitations_table.php", note: "Membentuk schema invitation table.", status: "Verified" },
      { path: "Backend/app/Models/TeamInvitation.php", note: "Model invitation dan relasi team/inviter.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/TeamInvitationController.php", note: "Endpoint show/send/list/accept invitation.", status: "Verified" },
    ],
    flows: [
      { title: "Invitation accept flow", status: "Verified", steps: ["Invitation dibuat dengan token dan expiry.", "Endpoint publik menampilkan detail invitation dan menerima acceptance.", "Acceptance dapat menggabungkan user ke team dan mengubah status invitation."] },
    ],
    dependencies: ["User", "Team", "TeamInvitationNotification"],
    sensitiveAreas: [{ title: "Public token flow", detail: "Accept invitation adalah surface publik sehingga token, expiry, dan assignment logic harus dijaga ketat.", status: "Verified" }],
    safeChangeGuide: ["Jangan ubah token/status semantics tanpa menguji acceptance end-to-end.", "Audit juga email notification content bila invitation payload berubah."],
    validationChecklist: ["Tes send invitation.", "Tes show invitation publik.", "Tes accept invitation."],
    affectedSurfaces: ["Backend/app/Http/Controllers/Api/TeamInvitationController.php", "Backend/app/Models/TeamInvitation.php"],
    relatedPageIds: ["backend/api-teams-members", "database/table-teams", "database/table-users"],
  },
{
    id: "database/table-settings",
    slug: ["database", "table-settings"],
    category: "database",
    title: "Table: settings",
    summary: "Key-value store grouped untuk platform settings, branding, public content, dan konfigurasi non-secret tingkat aplikasi.",
    audience: ["Super Admin", "Backend Developer"],
    overallStatus: "Verified",
    statusNote: "settings dipakai luas oleh SettingController, AdminPlatformController, dan frontend public settings hook.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Unique Field", value: "key" },
      { label: "Grouping", value: "group string default general" },
      { label: "Value Storage", value: "text nullable" },
    ],
    responsibilities: ["Menyimpan setting grouped untuk general/contact/social/seo/marketing/email dan area lain yang bersifat data-driven.", "Menjadi sumber data untuk /api/platform-settings dan sebagian besar admin settings UI."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_03_171631_create_settings_table.php", note: "Membentuk tabel settings dasar.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_04_000002_add_group_column_to_settings_table.php", note: "Menambah grouping per settings.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/SettingController.php", note: "API generic settings endpoints.", status: "Verified" },
    ],
    flows: [{ title: "Settings read/write flow", status: "Verified", steps: ["Admin menulis settings melalui endpoints atau screens admin.", "Public/frontend consumers membaca subset settings via /platform-settings.", "Grouping memudahkan pemisahan domain settings tanpa tabel terpisah terlalu banyak."] }],
    dependencies: ["AdminPlatformController", "usePlatformSettings hook", "Admin settings pages"],
    sensitiveAreas: [{ title: "Over-broad access", detail: "Generic settings endpoints harus diperlakukan sensitif karena dapat memengaruhi permukaan publik dan internal sekaligus.", status: "Verified" }],
    safeChangeGuide: ["Tentukan apakah nilai baru layak jadi settings database atau justru env runtime.", "Audit semua consumer public/admin saat menambah atau mengganti key."],
    validationChecklist: ["Tes read/write settings group terkait.", "Tes frontend consumers seperti navbar/footer/platform settings."],
    affectedSurfaces: ["Backend/app/Http/Controllers/Api/SettingController.php", "Frontend/src/hooks/use-platform-settings.ts", "Frontend/src/app/admin/settings/**/*"],
    relatedPageIds: ["operations/settings-environment", "backend/api-support-admin-ops", "database/table-email-settings"],
  },
{
    id: "database/table-email-settings",
    slug: ["database", "table-email-settings"],
    category: "database",
    title: "Table: email_settings",
    summary: "Tabel konfigurasi ringan untuk branding/template email seperti logo, warna utama, dan footer text.",
    audience: ["Super Admin", "Backend Developer"],
    overallStatus: "Partial",
    statusNote: "email_settings jelas ada dan dipakai EmailTemplateController, tetapi konsep email config/branding juga tersebar di settings group email.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Typical Use", value: "logo_url, primary_color, footer_text" },
      { label: "Singleton Pattern", value: "Kode banyak memakai first()" },
      { label: "Overlap", value: "Sebagian konfigurasi email lain hidup di settings table" },
    ],
    responsibilities: ["Menyimpan branding/template email sederhana.", "Menjadi basis preview atau konfigurasi tampilan email di area admin tertentu."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_03_173444_create_email_settings_table.php", note: "Membuat email_settings.", status: "Verified" },
      { path: "Backend/app/Models/EmailSetting.php", note: "Model email settings.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/EmailTemplateController.php", note: "Controller utama untuk email settings/template preview.", status: "Verified" },
    ],
    flows: [{ title: "Email branding flow", status: "Verified", steps: ["Admin screen membaca/menulis branding email.", "Controller mengambil row pertama dari email_settings.", "Template preview/branding flow kemudian memakai nilai ini."] }],
    dependencies: ["EmailTemplateController", "Admin email page", "Mail runtime"],
    sensitiveAreas: [{ title: "Concept duplication", detail: "Email config/branding juga muncul di settings group email, sehingga boundary antara email_settings dan settings harus dijelaskan dengan jujur.", status: "Partial" }],
    safeChangeGuide: ["Jangan samakan email_settings dengan env mail credentials.", "Jika menyederhanakan email config, audit EmailTemplateController dan AdminPlatformController bersama."],
    validationChecklist: ["Tes load/update email branding.", "Tes preview/test email jika terkait perubahan."],
    affectedSurfaces: ["Backend/app/Models/EmailSetting.php", "Backend/app/Http/Controllers/Api/EmailTemplateController.php", "Frontend/src/app/admin/email/page.tsx"],
    relatedPageIds: ["database/table-settings", "operations/email-notifications-support", "backend/api-support-admin-ops"],
  },
{
    id: "database/table-cash-books",
    slug: ["database", "table-cash-books"],
    category: "database",
    title: "Table: cash_books",
    summary: "Tabel kas tim untuk arus uang masuk/keluar beserta attachment dan activity log terkait.",
    audience: ["Backend Developer", "QA", "Team Ops"],
    overallStatus: "Verified",
    statusNote: "cash_books cukup lurus: UUID primary key, type in/out, amount/date, creator, team, dan attachment_path.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Enum", value: "type = in | out" },
      { label: "Important FKs", value: "created_by -> users.id, team_id -> teams.id" },
      { label: "Attachment", value: "attachment_path nullable" },
    ],
    responsibilities: ["Merekam pemasukan/pengeluaran tim.", "Menjadi dasar resource cash book di frontend dan activity trail finance tertentu."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_132012_create_cash_books_table.php", note: "Membuat tabel cash_books.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_02_134500_add_attachment_path_to_cash_books_table.php", note: "Menambah attachment_path.", status: "Verified" },
      { path: "Backend/app/Models/CashBook.php", note: "Model cash book dengan UUID dan activity log.", status: "Verified" },
    ],
    flows: [{ title: "Cash book record flow", status: "Verified", steps: ["Record kas dibuat dalam konteks team dan creator.", "Attachment opsional disimpan di R2 dan direferensikan via attachment_path.", "Frontend finance screens membaca resource cash book untuk list/detail/history."] }],
    dependencies: ["CashBookController", "CashBookResource", "R2 storage", "Lead/member finance pages"],
    sensitiveAreas: [{ title: "Object scope", detail: "Show/history/update/delete harus selalu dipandang sensitif karena terkait data kas tim.", status: "Partial" }],
    safeChangeGuide: ["Jika mengubah mapping field, audit request-field translation di CashBookController.", "Tes attachment upload/delete jika mengubah file behavior."],
    validationChecklist: ["Tes cash book create/show/update/delete.", "Tes attachment render/download."],
    affectedSurfaces: ["Backend/app/Models/CashBook.php", "Backend/app/Http/Controllers/Api/CashBookController.php", "Frontend/src/app/lead/finance/cash-book/**/*"],
    relatedPageIds: ["backend/api-finance", "database/finance", "operations/media-storage"],
  },
{
    id: "database/table-split-bills",
    slug: ["database", "table-split-bills"],
    category: "database",
    title: "Table: split_bills",
    summary: "Header tagihan patungan yang menghubungkan creator, team, due date, status, dan relasi ke bill_items serta recurring origins.",
    audience: ["Backend Developer", "QA"],
    overallStatus: "Partial",
    statusNote: "Schema split_bills telah mengalami alter penting dan status sekarang bertipe string; generated recurring linkage ke team perlu perhatian khusus.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Important FKs", value: "creator_id -> users.id, parent_recurring_bill_id -> recurring_bills.id, team_id -> teams.id" },
      { label: "Status Storage", value: "string default active" },
      { label: "Date Field", value: "due_date (hasil rename dari date)" },
    ],
    responsibilities: ["Menyimpan header tagihan patungan sebelum dibagi ke bill_items.", "Menjembatani split bill manual dan split bill hasil recurring generation."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_132013_create_split_bills_table.php", note: "Skema awal split_bills.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_02_135702_alter_split_bills_for_controller.php", note: "Rename field dan perubahan status/creator semantics.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_02_140003_add_parent_recurring_bill_id_to_split_bills_table.php", note: "Menambah relasi ke recurring bill.", status: "Verified" },
    ],
    flows: [{ title: "Split bill header flow", status: "Verified", steps: ["Split bill dibuat sebagai header tagihan bersama.", "Bill items kemudian dibentuk untuk tiap user yang terkait.", "Jika berasal dari recurring bill, parent_recurring_bill_id merekam asal template periodic-nya."] }],
    dependencies: ["BillItem table", "RecurringBillService", "SplitBillController", "SplitBillResource"],
    sensitiveAreas: [{ title: "Generated team context", detail: "Hasil generation recurring split bill perlu terus diaudit agar team_id tidak hilang dalam alur otomatis tertentu.", status: "Partial" }],
    safeChangeGuide: ["Baca create + alter migration sekaligus sebelum mengubah tabel ini.", "Jika mengubah status semantics, audit bill items, recurring flow, dan frontend badges/filters."],
    validationChecklist: ["Tes split bill manual CRUD.", "Tes split bill generated dari recurring flow."],
    affectedSurfaces: ["Backend/app/Http/Controllers/Api/SplitBillController.php", "Backend/app/Services/RecurringBillService.php", "Frontend/src/app/lead/finance/bills/**/*"],
    relatedPageIds: ["database/table-bill-items", "database/table-recurring-bills", "backend/api-finance"],
  },
{
    id: "database/table-bill-items",
    slug: ["database", "table-bill-items"],
    category: "database",
    title: "Table: bill_items",
    summary: "Detail porsi tagihan per user, termasuk status pembayaran, bukti, verifier, dan reminder timestamp.",
    audience: ["Backend Developer", "QA"],
    overallStatus: "Partial",
    statusNote: "bill_items jelas dipakai untuk pay/verify flow, tetapi status pentingnya ditegakkan terutama di level aplikasi, bukan enum/check DB yang ketat.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Important FKs", value: "split_bill_id -> split_bills.id, user_id -> users.id, verified_by -> users.id" },
      { label: "Status Values", value: "unpaid, pending_verification, paid" },
      { label: "Proof Fields", value: "proof_path, verified_at, reminder_sent_at" },
    ],
    responsibilities: ["Menyimpan state pembayaran tiap user dalam split bill.", "Menjadi dasar verify/proof workflow dan reminder automation."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_132016_create_bill_items_table.php", note: "Skema awal bill_items.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_02_135620_alter_bill_items_table.php", note: "Mengganti is_paid dengan status/proof_path/verified_by/verified_at.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_02_140002_add_reminder_sent_at_to_bill_items_table.php", note: "Menambah reminder_sent_at.", status: "Verified" },
    ],
    flows: [{ title: "Bill item payment flow", status: "Verified", steps: ["User membayar bill item dan mengunggah proof jika diperlukan.", "Verifier mengubah status menjadi paid atau mengembalikan ke unpaid sesuai hasil verifikasi.", "Reminder command menggunakan reminder_sent_at untuk mencegah spam pengingat berulang."] }],
    dependencies: ["BillItemController", "RemindBillItems command", "SplitBill table", "CashBook side-effects saat verify tertentu"],
    sensitiveAreas: [{ title: "Application-enforced statuses", detail: "Status bill item tidak dibatasi kuat oleh enum DB, jadi perubahan constants/strings di controller harus sangat hati-hati.", status: "Partial" }],
    safeChangeGuide: ["Jika menambah status baru, audit verify/pay logic, filters, badges, dan resources.", "Tes reminder flow jika menyentuh reminder_sent_at semantics."],
    validationChecklist: ["Tes pay flow.", "Tes verify accepted/rejected flow.", "Tes reminder behavior secara manual atau via command."],
    affectedSurfaces: ["Backend/app/Http/Controllers/Api/BillItemController.php", "Backend/app/Console/Commands/RemindBillItems.php", "Frontend finance bill detail screens"],
    relatedPageIds: ["database/table-split-bills", "backend/api-finance", "database/finance"],
  },
{
    id: "database/table-recurring-bills",
    slug: ["database", "table-recurring-bills"],
    category: "database",
    title: "Table: recurring_bills",
    summary: "Template tagihan berulang dengan frequency, interval, status, schedule timestamps, assignee_ids, dan konfigurasi reminder.",
    audience: ["Backend Developer", "Team Ops"],
    overallStatus: "Verified",
    statusNote: "recurring_bills adalah inti automation finance dan punya schema yang paling kaya di domain finance.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Frequency Enum", value: "daily, weekly, monthly, quarterly, yearly, custom_days" },
      { label: "Status Enum", value: "active, paused, ended" },
      { label: "Scheduling Fields", value: "start_date, end_date, last_generated_at, next_generation_at" },
    ],
    responsibilities: ["Menyimpan template periodic split bill generation.", "Menjadi pusat scheduling, assignment, dan lifecycle recurring finance."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_140001_create_recurring_bills_table.php", note: "Skema utama recurring bills.", status: "Verified" },
      { path: "Backend/app/Models/RecurringBill.php", note: "Model recurring bill dan casts terkait.", status: "Verified" },
      { path: "Backend/app/Services/RecurringBillService.php", note: "Service generation split bills dari recurring template.", status: "Verified" },
    ],
    flows: [{ title: "Recurring template flow", status: "Verified", steps: ["Admin/lead membuat recurring bill dengan frequency dan timing fields.", "Scheduler atau manual generate memakai template ini untuk membuat split bill baru.", "Generation timestamps membantu controller menentukan due/next generation behavior."] }],
    dependencies: ["RecurringBillController", "RecurringBillService", "GenerateRecurringBills command", "SplitBill table"],
    sensitiveAreas: [{ title: "Schema-controller parity", detail: "Dashboard/consumer yang membaca recurring data harus selalu dicek terhadap schema aktual seperti next_generation_at/status.", status: "Partial" }],
    safeChangeGuide: ["Jika mengubah scheduling fields, audit command, service, controller, dan dashboard widgets sekaligus.", "Tes active/paused/ended lifecycle sebelum deploy."],
    validationChecklist: ["Tes create/update/delete recurring bill.", "Tes manual generate.", "Tes scheduler behavior pada environment aman bila memungkinkan."],
    affectedSurfaces: ["Backend/app/Models/RecurringBill.php", "Backend/app/Services/RecurringBillService.php", "Backend/app/Console/Commands/GenerateRecurringBills.php", "Frontend recurring bill pages"],
    relatedPageIds: ["database/table-recurring-bill-generations", "database/table-split-bills", "backend/jobs-realtime-storage"],
  },
{
    id: "database/table-recurring-bill-generations",
    slug: ["database", "table-recurring-bill-generations"],
    category: "database",
    title: "Table: recurring_bill_generations",
    summary: "Link/history table yang menghubungkan recurring bill template dengan split bill hasil generation.",
    audience: ["Backend Developer", "QA"],
    overallStatus: "Verified",
    statusNote: "Tabel ini sederhana tetapi penting untuk histori generation dan tracing asal split bill otomatis.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Important FKs", value: "recurring_bill_id -> recurring_bills.id, split_bill_id -> split_bills.id" },
      { label: "Unique Constraint", value: "recurring_bill_id + split_bill_id" },
      { label: "Key Date", value: "generated_at" },
    ],
    responsibilities: ["Merekam histori setiap hasil generation recurring bill.", "Membantu trace split bill ke template asalnya."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_140004_create_recurring_bill_generations_table.php", note: "Skema recurring_bill_generations.", status: "Verified" },
      { path: "Backend/app/Models/RecurringBillGeneration.php", note: "Model generation history.", status: "Verified" },
      { path: "Backend/app/Services/RecurringBillService.php", note: "Service yang menulis row generation ini.", status: "Verified" },
    ],
    flows: [{ title: "Generation history flow", status: "Verified", steps: ["Setiap generate split bill dari recurring template dapat menulis row histori di tabel ini.", "Controller show/history recurring kemudian dapat memanfaatkan relasi ini untuk audit dan display."] }],
    dependencies: ["RecurringBill", "SplitBill", "RecurringBillService"],
    sensitiveAreas: [{ title: "Traceability", detail: "Jika service berhenti menulis row ini secara konsisten, histori recurring finance akan kehilangan jejak asal split bill otomatis.", status: "Inferred" }],
    safeChangeGuide: ["Jangan ubah unique/link semantics tanpa memikirkan histori yang sudah ada.", "Tes generation history read-back jika service logic berubah."],
    validationChecklist: ["Tes generation menghasilkan row histori.", "Tes recurring history endpoint atau consumer terkait."],
    affectedSurfaces: ["Backend/app/Models/RecurringBillGeneration.php", "Backend/app/Services/RecurringBillService.php", "Backend recurring history consumers"],
    relatedPageIds: ["database/table-recurring-bills", "database/table-split-bills", "backend/api-finance"],
  },
{
    id: "database/table-tasks",
    slug: ["database", "table-tasks"],
    category: "database",
    title: "Table: tasks",
    summary: "Task table untuk productivity board dengan status, priority, assignee, creator, due_date, position, dan team context.",
    audience: ["Backend Developer", "Frontend Developer"],
    overallStatus: "Verified",
    statusNote: "tasks cukup jelas dan menjadi basis board/list productivity di lead/member surfaces.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Status Enum", value: "todo, in_progress, done" },
      { label: "Priority Enum", value: "low, medium, high" },
      { label: "Ordering", value: "position integer default 0" },
    ],
    responsibilities: ["Menyimpan task board item tim.", "Mendukung assignment, status transition, due dates, dan ordering/reorder UI."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_132015_create_tasks_table.php", note: "Skema awal tasks.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_02_135830_alter_tasks_for_controller.php", note: "Rename assignee field dan menambah priority/creator_id.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_06_000001_add_position_to_tasks_table.php", note: "Menambah position untuk board ordering.", status: "Verified" },
    ],
    flows: [{ title: "Task board data flow", status: "Verified", steps: ["Task disimpan dengan team context, creator, assignee, priority, status, and ordering position.", "Frontend membaca resource ini untuk list/board dan mengirim patch status atau reorder sesuai interaksi pengguna."] }],
    dependencies: ["TaskController", "TaskResource", "TaskAssignedNotification", "Frontend productivity pages"],
    sensitiveAreas: [{ title: "Scope and ordering", detail: "Perubahan task scope atau position semantics dapat memengaruhi keamanan data dan UX kanban sekaligus.", status: "Partial" }],
    safeChangeGuide: ["Jika mengubah status/priority, audit enum usage di controller, resource, dan frontend badges.", "Jika mengubah position logic, uji reorder end-to-end."],
    validationChecklist: ["Tes task CRUD.", "Tes status patch.", "Tes reorder."],
    affectedSurfaces: ["Backend/app/Models/Task.php", "Backend/app/Http/Controllers/Api/TaskController.php", "Frontend productivity task pages"],
    relatedPageIds: ["backend/api-productivity", "database/productivity", "database/table-daily-logs"],
  },
{
    id: "database/table-daily-logs",
    slug: ["database", "table-daily-logs"],
    category: "database",
    title: "Table: daily_logs",
    summary: "Tabel laporan harian user dengan title, log_date, content, optional attachment, dan team context.",
    audience: ["Backend Developer", "Frontend Developer"],
    overallStatus: "Verified",
    statusNote: "daily_logs adalah domain yang relatif lurus, tetapi export dan ownership rules membuatnya tetap penting untuk audit perubahan.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Important FKs", value: "user_id -> users.id, team_id -> teams.id" },
      { label: "Core Fields", value: "title, log_date, content" },
      { label: "Attachment", value: "attachment_path nullable" },
    ],
    responsibilities: ["Menyimpan catatan kerja harian anggota tim.", "Menjadi dasar list/detail/export daily log di frontend."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_132014_create_daily_logs_table.php", note: "Skema awal daily_logs.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_02_135951_alter_daily_logs_table.php", note: "Menambah title pada daily_logs.", status: "Verified" },
      { path: "Backend/app/Models/DailyLog.php", note: "Model daily log.", status: "Verified" },
    ],
    flows: [{ title: "Daily log data flow", status: "Verified", steps: ["User membuat daily log dengan title/date/content/attachment.", "Backend mengelola ownership dan batasan tertentu pada update/delete.", "Export endpoint menyusun data log untuk kebutuhan pelaporan user/tim."] }],
    dependencies: ["DailyLogController", "DailyLogResource", "R2 attachment storage", "Frontend daily log pages"],
    sensitiveAreas: [{ title: "Ownership and export", detail: "Show/update/delete/export semantics harus selalu dipandang sensitif karena menyangkut laporan harian user dan lampiran yang bisa bersifat pribadi/tim.", status: "Partial" }],
    safeChangeGuide: ["Jika mengubah field log, audit export output juga.", "Tes attachment handling bila menyentuh file-related columns."],
    validationChecklist: ["Tes daily log CRUD.", "Tes export.", "Tes attachment upload/render."],
    affectedSurfaces: ["Backend/app/Models/DailyLog.php", "Backend/app/Http/Controllers/Api/DailyLogController.php", "Frontend productivity daily log pages"],
    relatedPageIds: ["backend/api-productivity", "database/productivity", "database/table-tasks"],
  },
{
    id: "database/table-team-media",
    slug: ["database", "table-team-media"],
    category: "database",
    title: "Table: team_media",
    summary: "Metadata storage untuk file tim: documents, gallery items, dan attachment tertentu seperti chat/media lainnya.",
    audience: ["Backend Developer", "Super Admin", "Content/Admin Ops"],
    overallStatus: "Verified",
    statusNote: "team_media adalah tabel sentral untuk library aset dan attachment file lintas beberapa modul.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Type Enum", value: "document, gallery" },
      { label: "Important FKs", value: "user_id -> users.id, team_id -> teams.id" },
      { label: "Storage Field", value: "file_path" },
    ],
    responsibilities: ["Menyimpan metadata file yang hidup di R2 atau storage disk terkait.", "Menjadi sumber list gallery/documents dan relasi attachment chat/media tertentu."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_133454_create_team_media_table.php", note: "Skema team_media.", status: "Verified" },
      { path: "Backend/app/Models/TeamMedia.php", note: "Model media metadata.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/MediaController.php", note: "List/upload/update/delete media library.", status: "Verified" },
    ],
    flows: [{ title: "Media metadata flow", status: "Verified", steps: ["Upload file menghasilkan object storage + metadata row di team_media.", "MediaController memfilter row ini menjadi documents/gallery lists.", "Chat atau feature lain dapat mereferensikan row media via media_id/file_path."] }],
    dependencies: ["R2 storage", "MediaController", "ChatController", "media picker/frontend consumers"],
    sensitiveAreas: [{ title: "Path vs URL semantics", detail: "file_path biasanya menyimpan storage key/path, bukan full URL, sehingga consumer harus konsisten saat merender atau menghapus file.", status: "Verified" }],
    safeChangeGuide: ["Jangan ubah storage path semantics tanpa mengaudit upload, display, dan delete flows.", "Tes media picker dan attachment consumers setelah perubahan."],
    validationChecklist: ["Tes upload/list/update/delete media.", "Tes gallery/document filters.", "Tes consumer yang membaca URL/path file."],
    affectedSurfaces: ["Backend/app/Models/TeamMedia.php", "Backend/app/Http/Controllers/Api/MediaController.php", "Frontend/src/app/admin/media/page.tsx"],
    relatedPageIds: ["backend/api-content-media", "operations/media-storage", "database/table-messages"],
  },
{
    id: "database/table-blogs",
    slug: ["database", "table-blogs"],
    category: "database",
    title: "Table: blogs",
    summary: "Tabel CMS/blog posts dengan slug, status publishing, featured image, category, tags, dan SEO metadata yang cukup kaya.",
    audience: ["Backend Developer", "Frontend Developer", "Content Admin"],
    overallStatus: "Partial",
    statusNote: "blogs kaya fitur tetapi telah berevolusi lewat beberapa migration; status, tags, dan SEO fields perlu dibaca bersama create + alter migrations untuk memahami schema final.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Unique Field", value: "slug" },
      { label: "Important FKs", value: "author_id -> users.id, team_id -> teams.id, category_id -> categories.id" },
      { label: "Status Values", value: "draft, published, scheduled" },
    ],
    responsibilities: ["Menyimpan konten artikel publik/internal tim beserta SEO metadata.", "Menjadi basis blog public pages dan admin/lead blog management pages."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_03_000003_create_blogs_table.php", note: "Skema awal blogs.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_05_180202_add_scheduled_status_to_blogs_table.php", note: "Menambah support scheduled publishing.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_07_000001_add_seo_fields_to_blogs_table.php", note: "Menambah SEO fields penting.", status: "Verified" },
      { path: "Backend/database/migrations/2026_07_07_000003_add_category_id_and_tags_to_blogs_table.php", note: "Menambah category_id dan tags.", status: "Verified" },
    ],
    flows: [{ title: "Blog publishing flow", status: "Verified", steps: ["Author/team leader/superadmin membuat blog beserta category, tags, featured image, dan SEO metadata.", "Public blog endpoints mengekspos content + metadata ini ke marketing/public frontend."] }],
    dependencies: ["BlogController", "BlogResource", "Category table", "R2 image storage", "Frontend blog pages"],
    sensitiveAreas: [
      { title: "Status constraint evolution", detail: "Status blogs telah melewati perubahan enum/string/check constraint sehingga migration chain harus dibaca utuh sebelum modifikasi baru.", status: "Partial" },
      { title: "Text fields cast as arrays", detail: "tags dan seo_keywords bukan kolom JSON murni tetapi diperlakukan seperti array di model, sehingga parser/serializer harus diaudit saat berubah.", status: "Partial" },
    ],
    safeChangeGuide: ["Jika mengubah blog schema, audit public blog pages dan admin/lead blog forms bersamaan.", "Tes slug uniqueness dan SEO field rendering setelah perubahan."],
    validationChecklist: ["Tes blog create/update/delete.", "Tes public blog detail/list.", "Tes SEO field persistence dan image handling."],
    affectedSurfaces: ["Backend/app/Models/Blog.php", "Backend/app/Http/Controllers/Api/BlogController.php", "Frontend/src/app/(marketing)/blog/**/*", "Frontend admin/lead blog pages"],
    relatedPageIds: ["backend/api-content-media", "database/table-categories", "database/content-media-support"],
  },
{
    id: "database/table-categories",
    slug: ["database", "table-categories"],
    category: "database",
    title: "Table: categories",
    summary: "Tabel kategori blog dengan slug unik yang dipakai untuk organisasi konten CMS.",
    audience: ["Backend Developer", "Content Admin"],
    overallStatus: "Verified",
    statusNote: "categories sederhana, tetapi route/controller parity tetap perlu diperhatikan di cluster API categories.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Unique Field", value: "slug" },
      { label: "Downstream FK", value: "blogs.category_id" },
      { label: "Main Use", value: "Organisasi blog posts" },
    ],
    responsibilities: ["Menyimpan kategori konten blog.", "Menjadi opsi classification pada blog creation/editing flows."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_07_000002_create_categories_table.php", note: "Skema categories.", status: "Verified" },
      { path: "Backend/app/Models/Category.php", note: "Model category dan slug generation behavior.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/CategoryController.php", note: "Category CRUD endpoints.", status: "Partial" },
    ],
    flows: [{ title: "Category flow", status: "Verified", steps: ["Admin/superadmin mengelola kategori.", "Blog posts mereferensikan category_id untuk grouping dan display."] }],
    dependencies: ["Blog table", "CategoryController", "Admin category management UI"],
    sensitiveAreas: [{ title: "Route/controller parity", detail: "Perlu terus dipastikan semua route categories benar-benar didukung method controller yang sesuai.", status: "Partial" }],
    safeChangeGuide: ["Jika mengubah slug semantics, audit blog URLs, filters, dan admin forms.", "Tes full category CRUD setelah perubahan."],
    validationChecklist: ["Tes category create/update/delete.", "Tes category assignment di blog."],
    affectedSurfaces: ["Backend/app/Models/Category.php", "Backend/app/Http/Controllers/Api/CategoryController.php", "Frontend admin categories page"],
    relatedPageIds: ["database/table-blogs", "backend/api-content-media", "database/content-media-support"],
  },
{
    id: "database/table-contact-messages",
    slug: ["database", "table-contact-messages"],
    category: "database",
    title: "Table: contact_messages",
    summary: "Inbox pesan dari form kontak publik, termasuk status read/unread untuk triage admin.",
    audience: ["Super Admin", "Support Engineer"],
    overallStatus: "Verified",
    statusNote: "contact_messages adalah domain sederhana tetapi penting karena menjadi gerbang support/public inquiry.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Core Fields", value: "first_name, last_name, email, company, message" },
      { label: "Read Flag", value: "is_read boolean default false" },
      { label: "Ingress", value: "POST /api/contact" },
    ],
    responsibilities: ["Menyimpan contact form submissions dari publik.", "Menjadi sumber inbox admin untuk pesan yang masuk."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_04_000001_create_contact_messages_table.php", note: "Skema contact_messages.", status: "Verified" },
      { path: "Backend/app/Models/ContactMessage.php", note: "Model contact message.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/ContactController.php", note: "Public store + admin list/mark read.", status: "Verified" },
    ],
    flows: [{ title: "Contact intake flow", status: "Verified", steps: ["Publik mengirim pesan melalui contact form.", "Backend menyimpan pesan ke contact_messages dengan is_read=false.", "Superadmin dapat membaca inbox dan menandai pesan sebagai read."] }],
    dependencies: ["ContactController", "Admin support/contact screens", "Public contact page"],
    sensitiveAreas: [{ title: "PII handling", detail: "Pesan kontak berisi email/nama/perusahaan sehingga harus diperlakukan sebagai data sensitif support.", status: "Verified" }],
    safeChangeGuide: ["Jangan mengubah shape contact submission tanpa mengaudit form publik dan inbox admin.", "Jaga throttling dan data retention policy bila diperluas."],
    validationChecklist: ["Tes submit contact form.", "Tes admin contact list/read flow."],
    affectedSurfaces: ["Backend/app/Models/ContactMessage.php", "Backend/app/Http/Controllers/Api/ContactController.php", "Frontend public contact/help pages"],
    relatedPageIds: ["backend/api-support-admin-ops", "operations/email-notifications-support", "database/table-tickets"],
  },
{
    id: "database/table-tickets",
    slug: ["database", "table-tickets"],
    category: "database",
    title: "Table: tickets",
    summary: "Tabel support tickets dari team leader ke superadmin dengan category, priority, status, dan optional attachment.",
    audience: ["Super Admin", "Support Engineer", "Backend Developer"],
    overallStatus: "Verified",
    statusNote: "tickets merupakan domain support internal yang cukup jelas dan punya lifecycle status eksplisit di DB.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Important FKs", value: "team_id -> teams.id, user_id -> users.id" },
      { label: "Category Enum", value: "bug, feature, billing, other" },
      { label: "Status Enum", value: "open, in_progress, resolved, closed" },
    ],
    responsibilities: ["Menyimpan support issue internal dari lead ke admin.", "Menjadi dasar lead ticket pages dan admin ticket triage/status update."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_07_043232_create_tickets_table.php", note: "Skema tickets.", status: "Verified" },
      { path: "Backend/app/Models/Ticket.php", note: "Model ticket.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/TicketController.php", note: "Lead-facing ticket endpoints.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/AdminTicketController.php", note: "Admin-facing ticket triage/status update.", status: "Verified" },
    ],
    flows: [{ title: "Ticket support flow", status: "Verified", steps: ["Lead membuat ticket dalam konteks team.", "Admin membaca dan mengubah status ticket selama proses support.", "Attachment opsional dapat ikut tersimpan untuk konteks issue/support evidence."] }],
    dependencies: ["Team and User tables", "R2 attachment handling", "Admin tickets UI", "Lead tickets UI"],
    sensitiveAreas: [{ title: "Support SLA semantics", detail: "Perubahan status/category/priority dapat memengaruhi operasional support dan reporting internal.", status: "Verified" }],
    safeChangeGuide: ["Jangan mengubah enum/status tanpa mengaudit UI filters, badge warna, dan business workflow support.", "Tes attachment flow bila file semantics disentuh."],
    validationChecklist: ["Tes lead ticket create/show.", "Tes admin ticket list/show/status update."],
    affectedSurfaces: ["Backend/app/Models/Ticket.php", "Backend/app/Http/Controllers/Api/TicketController.php", "Backend/app/Http/Controllers/Api/AdminTicketController.php", "Frontend ticket pages"],
    relatedPageIds: ["backend/api-support-admin-ops", "operations/email-notifications-support", "database/table-contact-messages"],
  },
{
    id: "database/table-conversations",
    slug: ["database", "table-conversations"],
    category: "database",
    title: "Table: conversations",
    summary: "Header ruang chat tim untuk general group atau DM conversations.",
    audience: ["Backend Developer", "Frontend Developer"],
    overallStatus: "Verified",
    statusNote: "conversations adalah root chat domain dan mengikat team context untuk group/dm rooms.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Important FK", value: "team_id -> teams.id" },
      { label: "Type Enum", value: "group, dm" },
      { label: "Special Behavior", value: "General group dapat dibuat otomatis" },
    ],
    responsibilities: ["Menyimpan room header untuk chat tim dan DM.", "Menjadi parent bagi participants dan messages."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_07_044858_create_conversations_table.php", note: "Skema conversations.", status: "Verified" },
      { path: "Backend/app/Models/Conversation.php", note: "Model conversation.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/ChatController.php", note: "Conversation discovery dan DM/group initialization logic.", status: "Verified" },
    ],
    flows: [{ title: "Conversation discovery flow", status: "Verified", steps: ["Frontend meminta daftar conversation untuk team tertentu.", "Backend dapat membuat General group atau DM room yang belum ada.", "Participants dan messages kemudian menentukan siapa yang boleh membaca/menulis room tersebut."] }],
    dependencies: ["Team", "ConversationParticipant", "Message", "ChatController"],
    sensitiveAreas: [{ title: "Auto-creation side effects", detail: "getConversations/startDm dapat menciptakan room baru sebagai side effect, jadi perubahan logic harus diuji hati-hati.", status: "Verified" }],
    safeChangeGuide: ["Tes existing room lookup dan room auto-creation behavior bersama-sama.", "Jangan ubah type semantics tanpa mengaudit consumers frontend chat."],
    validationChecklist: ["Tes conversations list.", "Tes general group existence.", "Tes DM start flow."],
    affectedSurfaces: ["Backend/app/Models/Conversation.php", "Backend/app/Http/Controllers/Api/ChatController.php", "Frontend chat interface"],
    relatedPageIds: ["backend/api-realtime-chat", "database/table-conversation-participants", "database/table-messages"],
  },
{
    id: "database/table-conversation-participants",
    slug: ["database", "table-conversation-participants"],
    category: "database",
    title: "Table: conversation_participants",
    summary: "Pivot peserta conversation beserta last_read_at untuk state membership/read tracking chat.",
    audience: ["Backend Developer"],
    overallStatus: "Verified",
    statusNote: "Pivot ini sederhana tetapi sangat penting untuk authorization di channel chat dan message retrieval.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Important FKs", value: "conversation_id -> conversations.id, user_id -> users.id" },
      { label: "Unique Constraint", value: "conversation_id + user_id" },
      { label: "Read Tracking", value: "last_read_at nullable" },
    ],
    responsibilities: ["Mencatat siapa peserta tiap conversation.", "Mendukung authorization dan read tracking di chat domain."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_07_044903_create_conversation_participants_table.php", note: "Skema participants pivot.", status: "Verified" },
      { path: "Backend/app/Models/ConversationParticipant.php", note: "Model participants pivot.", status: "Verified" },
      { path: "Backend/routes/channels.php", note: "Channel auth mengecek membership conversation berdasarkan participants.", status: "Verified" },
    ],
    flows: [{ title: "Conversation membership flow", status: "Verified", steps: ["Participant rows menentukan membership sebuah room.", "ChatController dan channel auth membaca pivot ini untuk memberi atau menolak akses.", "last_read_at dapat dipakai untuk unread/read state tracking." ] }],
    dependencies: ["Conversation", "User", "ChatController", "channels.php auth"],
    sensitiveAreas: [{ title: "Membership authorization", detail: "Jika participant rows salah atau tidak dibuat konsisten, user bisa kehilangan akses sah atau mendapat akses ke room yang salah.", status: "Verified" }],
    safeChangeGuide: ["Jangan ubah uniqueness atau FK behavior tanpa mengaudit auth channel dan ChatController.", "Tes participant creation dan read access bersama-sama."],
    validationChecklist: ["Tes participant uniqueness.", "Tes room access oleh participant vs non-participant."],
    affectedSurfaces: ["Backend/app/Models/ConversationParticipant.php", "Backend/routes/channels.php", "Backend/app/Http/Controllers/Api/ChatController.php"],
    relatedPageIds: ["database/table-conversations", "database/table-messages", "backend/api-realtime-chat"],
  },
{
    id: "database/table-messages",
    slug: ["database", "table-messages"],
    category: "database",
    title: "Table: messages",
    summary: "Tabel pesan individual pada conversation, termasuk text content, media_id, dan attachment_path.",
    audience: ["Backend Developer", "Frontend Developer"],
    overallStatus: "Verified",
    statusNote: "messages adalah inti data chat dan terhubung ke conversation, sender, dan optional TeamMedia attachment.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Important FKs", value: "conversation_id -> conversations.id, sender_id -> users.id, media_id -> team_media.id" },
      { label: "Content Fields", value: "content nullable, attachment_path nullable" },
      { label: "Retention", value: "messages older than 7 days can be cleaned up by scheduler" },
    ],
    responsibilities: ["Menyimpan pesan chat individual beserta relasi media/attachment.", "Menjadi basis getMessages/sendMessage dan event broadcast chat."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_07_044909_create_messages_table.php", note: "Skema messages.", status: "Verified" },
      { path: "Backend/app/Models/Message.php", note: "Model message.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/ChatController.php", note: "Read/send message endpoints.", status: "Verified" },
      { path: "Backend/routes/console.php", note: "Retention cleanup untuk old messages dan attachments.", status: "Verified" },
    ],
    flows: [{ title: "Message lifecycle", status: "Verified", steps: ["User mengirim text atau file melalui ChatController.", "Message row dibuat dengan conversation/sender dan optional media reference.", "Old messages dan attachment dapat dibersihkan scheduler setelah 7 hari."] }],
    dependencies: ["Conversation", "User", "TeamMedia", "MessageSent event", "Chat frontend"],
    sensitiveAreas: [{ title: "Retention cleanup", detail: "Perubahan skema/path message attachment harus mempertimbangkan scheduler cleanup agar tidak meninggalkan file yatim atau pesan hantu.", status: "Verified" }],
    safeChangeGuide: ["Jika mengubah attachment semantics, audit ChatController dan routes/console cleanup sekaligus.", "Tes text-only dan file-only message scenarios."],
    validationChecklist: ["Tes send text message.", "Tes send file message.", "Tes cleanup assumptions pada old messages."],
    affectedSurfaces: ["Backend/app/Models/Message.php", "Backend/app/Http/Controllers/Api/ChatController.php", "Backend/routes/console.php", "Frontend chat interface"],
    relatedPageIds: ["database/table-team-media", "database/table-conversations", "backend/api-realtime-chat"],
  },
{
    id: "database/table-notifications",
    slug: ["database", "table-notifications"],
    category: "database",
    title: "Table: notifications",
    summary: "Tabel notifikasi Laravel berbasis UUID dan morph relation untuk menyimpan payload notifikasi user.",
    audience: ["Backend Developer", "Frontend Developer", "Support"],
    overallStatus: "Partial",
    statusNote: "Schema notifications jelas, tetapi payload-nya polymorphic/JSON tergantung class notification sehingga dokumentasi payload harus dibaca per notification class juga.",
    facts: [
      { label: "Primary Key", value: "UUID" },
      { label: "Relation Type", value: "morphs(notifiable)" },
      { label: "Core Fields", value: "type, data, read_at" },
      { label: "Consumers", value: "NotificationController + SSE/frontend header" },
    ],
    responsibilities: ["Menyimpan DB notifications untuk user notifiable.", "Menjadi sumber inbox notifikasi di frontend dan sebagian event realtime."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_134932_create_notifications_table.php", note: "Skema notifications.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/NotificationController.php", note: "List/read/read-all notifications.", status: "Verified" },
      { path: "Backend/app/Notifications", note: "Kumpulan notification classes yang membentuk payload ke tabel ini.", status: "Verified" },
    ],
    flows: [{ title: "Notification inbox flow", status: "Verified", steps: ["Notification classes menulis payload ke notifications table.", "Frontend membaca list notifications via NotificationController.", "Sebagian update juga dapat dikirim via SSE event stream ke frontend." ] }],
    dependencies: ["User Notifiable trait", "NotificationController", "SSE/frontend header dropdown"],
    sensitiveAreas: [{ title: "Polymorphic payloads", detail: "Karena data bersifat JSON polymorphic per notification class, perubahan payload harus diaudit di semua consumer UI dan SSE handlers yang terkait.", status: "Partial" }],
    safeChangeGuide: ["Jika menambah/mengubah notification class, audit UI consumers dan mark read flow.", "Tes read/read-all plus realtime delivery bila ada event terkait."],
    validationChecklist: ["Tes notification list.", "Tes mark read/read-all.", "Tes payload rendering di frontend header/dropdown."],
    affectedSurfaces: ["Backend/app/Http/Controllers/Api/NotificationController.php", "Backend/app/Notifications/*", "Frontend header/notification consumers"],
    relatedPageIds: ["backend/api-realtime-chat", "operations/email-notifications-support", "architecture/integrations-realtime"],
  },
{
    id: "database/table-roles",
    slug: ["database", "table-roles"],
    category: "database",
    title: "Table: roles",
    summary: "Master role table dari Spatie Permission yang menyimpan role global seperti super_admin, team_leader, dan member.",
    audience: ["Backend Developer", "Super Admin"],
    overallStatus: "Partial",
    statusNote: "roles jelas sebagai master RBAC, tetapi peran efektif sistem juga bergantung pada users.role string di tabel users.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Unique Constraint", value: "name + guard_name" },
      { label: "Teams Mode", value: "config permission teams=false" },
      { label: "Seeded Roles", value: "super_admin, team_leader, member" },
    ],
    responsibilities: ["Menyimpan definisi role global untuk paket Spatie.", "Menjadi sumber role master yang dihubungkan ke users via pivot tables."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_131958_create_permission_tables.php", note: "Membuat roles dan tabel RBAC lain.", status: "Verified" },
      { path: "Backend/config/permission.php", note: "Menunjukkan teams=false dan cache semantics RBAC.", status: "Verified" },
      { path: "Backend/database/seeders/RoleSeeder.php", note: "Seed role awal aplikasi.", status: "Verified" },
    ],
    flows: [{ title: "Role master flow", status: "Verified", steps: ["Seeder membuat role dasar.", "MemberController dan Auth/Invitation flow kemudian assign/sync role ini ke user.", "Frontend tetap juga membaca users.role string untuk redirect UI tertentu."] }],
    dependencies: ["permissions table", "model_has_roles pivot", "users.role string"],
    sensitiveAreas: [{ title: "Role duplication", detail: "roles table bukan satu-satunya sumber role efektif karena users.role juga hidup di sistem.", status: "Partial" }],
    safeChangeGuide: ["Jika menambah role baru, audit users.role semantics dan frontend redirect/menu logic.", "Tes seed, assign, dan permission matrix bersama-sama."],
    validationChecklist: ["Tes role assignment.", "Tes role-based access di admin/lead/member surfaces."],
    affectedSurfaces: ["Backend/config/permission.php", "Backend/database/seeders/RoleSeeder.php", "Backend MemberController", "Frontend auth/sidebar logic"],
    relatedPageIds: ["backend/auth-rbac", "database/table-permissions", "database/table-model-has-roles"],
  },
{
    id: "database/table-permissions",
    slug: ["database", "table-permissions"],
    category: "database",
    title: "Table: permissions",
    summary: "Master permission table dari Spatie Permission untuk capability granular seperti manage_members, write_split_bill, view_tasks, dsb.",
    audience: ["Backend Developer", "Super Admin"],
    overallStatus: "Partial",
    statusNote: "permissions adalah master capability granular, tetapi pemakaiannya di frontend/sidebar/controller harus selalu dibaca bersama role dan users.role semantics.",
    facts: [
      { label: "Primary Key", value: "bigint unsigned (id)" },
      { label: "Unique Constraint", value: "name + guard_name" },
      { label: "Typical Permissions", value: "manage_members, manage_permissions, write_split_bill, view_tasks" },
      { label: "Usage", value: "Controller guards + frontend menu filtering" },
    ],
    responsibilities: ["Menyimpan capability granular sistem.", "Menjadi sumber permission matrix yang ditautkan ke roles dan/atau user langsung."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_131958_create_permission_tables.php", note: "Membuat permissions table.", status: "Verified" },
      { path: "Backend/database/seeders/RoleSeeder.php", note: "Seeder permission awal.", status: "Verified" },
      { path: "Frontend/src/components/layout/sidebar.tsx", note: "Contoh pemakaian permission untuk memfilter menu lead/member.", status: "Verified" },
    ],
    flows: [{ title: "Permission flow", status: "Verified", steps: ["Seeder atau admin panel menetapkan permissions master.", "Role dan user kemudian menerima permissions via pivot tables.", "Controller dan frontend menus membaca permissions ini untuk membatasi aksi/fitur."] }],
    dependencies: ["roles", "model_has_permissions", "role_has_permissions", "frontend sidebar filtering"],
    sensitiveAreas: [{ title: "Capability drift", detail: "Perubahan nama permission dapat merusak guard controller dan juga menu frontend yang membaca string permission yang sama.", status: "Verified" }],
    safeChangeGuide: ["Jika mengganti permission name, cari semua consumer backend dan frontend.", "Sinkronkan seeder, controller checks, dan menu filtering sekaligus."],
    validationChecklist: ["Tes permission grant/revoke.", "Tes menu visibility dan endpoint access yang terkait."],
    affectedSurfaces: ["Backend/database/seeders/RoleSeeder.php", "Backend MemberController", "Frontend/src/components/layout/sidebar.tsx"],
    relatedPageIds: ["backend/auth-rbac", "database/table-roles", "database/table-role-has-permissions"],
  },
{
    id: "database/table-model-has-roles",
    slug: ["database", "table-model-has-roles"],
    category: "database",
    title: "Table: model_has_roles",
    summary: "Pivot polymorphic antara model dan role; pada TeamVora terutama digunakan untuk menghubungkan users ke roles Spatie.",
    audience: ["Backend Developer"],
    overallStatus: "Partial",
    statusNote: "Pivot ini penting untuk role assignment, tetapi efektivitas role sistem tetap harus dibaca bersama users.role string dan permission pivots lain.",
    facts: [
      { label: "Primary Key", value: "composite (role_id, model_id, model_type)" },
      { label: "Important FK", value: "role_id -> roles.id" },
      { label: "Polymorphic", value: "model_type + model_id" },
      { label: "Teams Mode", value: "no team_id because teams=false" },
    ],
    responsibilities: ["Mencatat role assignment ke user/model lain via Spatie.", "Menjadi pivot utama untuk HasRoles trait."] ,
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_131958_create_permission_tables.php", note: "Membuat model_has_roles pivot.", status: "Verified" },
      { path: "Backend/app/Models/User.php", note: "HasRoles trait memanfaatkan pivot ini.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/MemberController.php", note: "syncRoles()/role assignment flows.", status: "Verified" },
    ],
    flows: [{ title: "Role assignment persistence", status: "Verified", steps: ["User diberi role via assignRole/syncRoles.", "Spatie menulis relasi ke model_has_roles.", "Controller/frontends lalu membaca role/permission result bersama users.role."] }],
    dependencies: ["roles", "users", "HasRoles trait", "MemberController"],
    sensitiveAreas: [{ title: "Consistency with users.role", detail: "Pivot ini saja tidak cukup menggambarkan role efektif aplikasi karena users.role juga dipakai luas di frontend/backend.", status: "Partial" }],
    safeChangeGuide: ["Jangan mengubah assignRole/syncRoles flow tanpa mengecek users.role sync behavior.", "Tes impersonation/login/menu role-based setelah perubahan."],
    validationChecklist: ["Tes role assignment persistence.", "Tes role-based UI redirect/menu."],
    affectedSurfaces: ["Backend/app/Models/User.php", "Backend/app/Http/Controllers/Api/MemberController.php", "Frontend role consumers"],
    relatedPageIds: ["database/table-roles", "database/table-users", "backend/auth-rbac"],
  },
{
    id: "database/table-model-has-permissions",
    slug: ["database", "table-model-has-permissions"],
    category: "database",
    title: "Table: model_has_permissions",
    summary: "Pivot polymorphic antara model dan permission untuk direct grants ke user/model tertentu.",
    audience: ["Backend Developer"],
    overallStatus: "Partial",
    statusNote: "Pivot ini dipakai untuk permission granular user-level, terutama melalui MemberController dan frontend menu filtering outcomes.",
    facts: [
      { label: "Primary Key", value: "composite (permission_id, model_id, model_type)" },
      { label: "Important FK", value: "permission_id -> permissions.id" },
      { label: "Polymorphic", value: "model_type + model_id" },
      { label: "Typical Use", value: "Direct permission grants ke user" },
    ],
    responsibilities: ["Menyimpan permission langsung ke user/model tertentu di luar role mapping.", "Menjadi basis granular override capability di aplikasi."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_131958_create_permission_tables.php", note: "Membuat model_has_permissions pivot.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/MemberController.php", note: "syncPermissions() menulis pivot ini.", status: "Verified" },
      { path: "Frontend/src/components/layout/sidebar.tsx", note: "Frontend membaca permissions efektif hasil relasi ini untuk memfilter menu.", status: "Verified" },
    ],
    flows: [{ title: "Direct permission grant flow", status: "Verified", steps: ["Admin menyetel permission langsung ke user.", "Spatie menulis relasi ke model_has_permissions.", "User effective permissions kemudian memengaruhi access di controller dan menu frontend."] }],
    dependencies: ["permissions", "users", "MemberController", "frontend menu filtering"],
    sensitiveAreas: [{ title: "Hidden permission sources", detail: "Akses user bisa datang dari role atau direct permission grants, jadi debugging access issue harus memeriksa keduanya.", status: "Verified" }],
    safeChangeGuide: ["Jika mengubah syncPermissions flow, tes endpoint dan sidebar visibility.", "Dokumentasikan direct grants vs role grants dengan jelas untuk admin ops."],
    validationChecklist: ["Tes grant/revoke permission langsung ke user.", "Tes endpoint/menu yang bergantung pada permission tersebut."],
    affectedSurfaces: ["Backend/app/Http/Controllers/Api/MemberController.php", "Frontend/src/components/layout/sidebar.tsx", "Admin RBAC UI"],
    relatedPageIds: ["database/table-permissions", "database/table-role-has-permissions", "backend/auth-rbac"],
  },
{
    id: "database/table-role-has-permissions",
    slug: ["database", "table-role-has-permissions"],
    category: "database",
    title: "Table: role_has_permissions",
    summary: "Pivot many-to-many yang membentuk permission matrix tiap role di sistem Spatie RBAC.",
    audience: ["Backend Developer", "Super Admin"],
    overallStatus: "Partial",
    statusNote: "Pivot ini adalah jantung matriks RBAC role->permission, tetapi harus tetap dibaca bersama users.role dan direct user permissions untuk gambaran access penuh.",
    facts: [
      { label: "Primary Key", value: "composite (permission_id, role_id)" },
      { label: "Important FKs", value: "permission_id -> permissions.id, role_id -> roles.id" },
      { label: "Main Use", value: "Role permission matrix" },
      { label: "Mutated By", value: "RoleSeeder and admin RBAC flows" },
    ],
    responsibilities: ["Menghubungkan role ke capability granular.", "Menjadi basis permission matrix yang diubah dari admin RBAC flows atau seeding."],
    keyFiles: [
      { path: "Backend/database/migrations/2026_07_02_131958_create_permission_tables.php", note: "Membuat role_has_permissions pivot.", status: "Verified" },
      { path: "Backend/database/seeders/RoleSeeder.php", note: "Seed awal matriks role-permission.", status: "Verified" },
      { path: "Backend/app/Http/Controllers/Api/MemberController.php", note: "updateRolePermissions() menyentuh pivot ini.", status: "Verified" },
    ],
    flows: [{ title: "Role permission matrix flow", status: "Verified", steps: ["Seeder atau admin UI menetapkan permission matrix per role.", "Spatie membaca pivot ini saat menghitung effective permissions role/user.", "Frontend dan backend guard kemudian memanfaatkan hasil kalkulasi itu."] }],
    dependencies: ["roles", "permissions", "MemberController", "frontend permission consumers"],
    sensitiveAreas: [{ title: "Matrix-wide impact", detail: "Perubahan satu mapping di pivot ini dapat mengubah akses banyak user sekaligus jika mereka berbagi role yang sama.", status: "Verified" }],
    safeChangeGuide: ["Tes role matrix changes dengan user nyata tiap role.", "Jangan ubah mapping tanpa mengecek UI admin RBAC dan menu frontend."] ,
    validationChecklist: ["Tes role permission sync.", "Tes endpoint access dan menu visibility untuk role terdampak."],
    affectedSurfaces: ["Backend/database/seeders/RoleSeeder.php", "Backend/app/Http/Controllers/Api/MemberController.php", "Frontend admin RBAC page", "Frontend sidebars"],
    relatedPageIds: ["database/table-roles", "database/table-permissions", "backend/auth-rbac"],
  }
];